name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions: "write-all"

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Zip dist directory
        run: cd dist && zip -r ../duke-prompts.zip .

      - name: Create Release and Upload Asset
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          TAG=${GITHUB_REF_NAME}
          gh release create $TAG 'duke-prompts.zip#Duke Prompts' --title "Release $TAG" --generate-notes

      - name: Bump the version in package.json with the tag
        run: |
          TAG=${GITHUB_REF_NAME}
          npm version $TAG --no-git-tag-version
          git add package.json
          git commit -m "Bump version to $TAG"
          git push

      - name: Publish to npm
        uses: actions/checkout@v5

      - name: Setup Node.js # Setup .npmrc file to publish to npm
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org/"
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
